### ISSUE TITLE
Divide by Zero error in DashBoard

### ISSUE THREAD

**Issue by stevebond007** [alexziskind1/rpstrackeraspcore#2]
When selecting one of the buttons 3, 6 or 12 months I get a Divide by Zero Error:

DivideByZeroException: Attempted to divide by zero.
decimal.FCallDivide(ref decimal d1, ref decimal d2)
decimal.op_Division(decimal d1, decimal d2)
RPS.Web.Pages.DashboardModel.get_IssueCloseRate() in Dashboard.cshtml.cs
+
        public decimal IssueCloseRate { get { return Math.Round((decimal)IssueCountClosed / (decimal)IssueCountActive * 100m, 2); } }
RPS.Web.Pages.Pages_Dashboard.ExecuteAsync() in Dashboard.cshtml
+
                        <strong>@Model.IssueCloseRate</strong>
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)

The reason is that the data is so old that there are no issues in the period.

One solution is to update the dates in the JSON file.

The proper solution is to change line 23 to expect the possiblility of zero issues as shown here:

public decimal IssueCloseRate { get { return IssueCountActive > 0 ? Math.Round((decimal)IssueCountClosed / (decimal)IssueCountActive * 100m, 2) : 0; } }

Great tutorial though, thanks!

**Comment by alexziskind1** [comment]
The provided static data file has items with dates in them (fs-items.json file). Just do a find and replace. Change 2019 to 2020 and change 2018 to 2019. Then you're all set
